name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Установка Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Установка зависимостей и запуск flake8
        run: |
          python -m pip install --upgrade pip
          pip install flake8
          pip install -r backend/requirements.txt
          echo "🔍 Проверка PEP8..."
          flake8 backend --exclude migrations --max-line-length=79

      - name: Установка Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Установка зависимостей и сборка фронтенда
        run: |
          npm ci --legacy-peer-deps
          CI=false npm run build
        working-directory: frontend

      - name: Архивация build-папки
        run: tar -czf build.tar.gz -C frontend/build .

      - name: Копирование build на сервер
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          source: 'build.tar.gz'
          target: '/home/${{ secrets.SERVER_USER }}/foodgram/frontend'

      - name: Деплой на сервер
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          script: |
            cd /home/${{ secrets.SERVER_USER }}/foodgram/frontend

            echo '🧹 Очистка старого build...'
            rm -rf build
            mkdir build

            echo '📦 Распаковка свежего build...'
            tar -xzf build.tar.gz -C build
            rm build.tar.gz

            echo '📂 Проверка содержимого build:'
            ls -la build

            echo '📦 Деплой контейнеров...'
            cd ../infra
            sudo docker compose down
            sudo docker compose pull
            sudo docker compose up -d --build
